name: "Hello World"
description: "Greet someone"
inputs:
  slack-bot-token:
    description: "Slack bot token"
    required: true
  slack-channel-id:
    description: "Slack channel id"
    required: true
  slack-ts:
    description: "update slack message"
    required: false
    default: ""
  android-status:
    description: "[start|success|fail|cancel]"
    required: false
    default: "start"
  ios-status:
    description: "[start|success|fail|cancel]"
    required: false
    default: "start"
  android-build-time:
    description: ""
    required: false
    default: ""
  ios-build-time:
    description: ""
    required: false
    default: ""
  android-eta:
    description: ""
    required: false
    default: ""
  ios-eta:
    description: ""
    required: false
    default: ""
  github-action-url:
    description: ""
    required: true
    default: ""
  version-nr:
    description: ""
    required: false
    default: ""
  branch:
    description: ""
    required: true
  jira-url:
    description: ""
    required: false
    default: ""
  errors:
    description: ""
    required: false
    default: false
outputs:
  ts:
    description: "Slack message timestamp"
    value: ${{ steps.launch_sequence.outputs.ts }}
runs:
  using: "composite"
  steps:
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: Create variables for next job
      run: setVariables.sh
      shell: bash
      id: initVars
      env:
        ANDROID_STATUS: ${{ inputs.android-status }}
        IOS_STATUS: ${{ inputs.ios-status }}
        SLACK_BOT_TOKEN: ${{ inputs.slack-bot-token }}
        SLACK_CHANNEL_ID: ${{ inputs.slack-channel-id }}
        ANDROID_BUILD_TIME: ${{ inputs.android-build-time }}
        IOS_BUILD_TIME: ${{ inputs.ios-build-time }}
        GITHUB_ACTION_URL: ${{ inputs.github-action-url }}
        VERSION_NR: ${{ inputs.version-nr }}
        BRANCH: ${{ inputs.branch }}
        JIRA_URL: ${{ inputs.jira-url }}
        ANDROID_ETA: ${{ inputs.android-eta }}
        IOS_ETA: ${{ inputs.ios-eta }}

    - name: Send or update slack message
      id: launch_sequence
      uses: slackapi/slack-github-action@v2.0.0
      with:
        method: ${{ inputs.slack-ts && 'chat.update' || 'chat.postMessage' }}
        token: ${{ inputs.slack-bot-token }}
        errors: ${{ inputs.errors }}
        payload: |
          channel: ${{ inputs.slack-channel-id }}
          ${{ inputs.slack-ts && format('ts: {0}', inputs.slack-ts) || '' }}
          text: ":nors: *Deployment ${{ steps.initVars.outputs.STATUS_TEXT }}*"
          attachments:
            - color: ${{ steps.initVars.outputs.STATUS_TEXT }}
              blocks:
                - type: "section"
                  fields: 
                    - type: "mrkdwn"
                      text: "*Version:* ${{ inputs.version-nr && format('{0}', inputs.version-nr) || 'Generating ...' }}"
                    - type: "mrkdwn"
                      text: "*To test:* ${{ inputs.jira-url && format('<{0}|Jira>', inputs.jira-url) || 'Generating ...' }}"
                - type: "divider"
                - type: "section"
                  fields: 
                    - type: "mrkdwn"
                      text: "${{ steps.initVars.outputs.ANDROID_STATUS_ICON }} *Android*"
                    - type: "mrkdwn"
                      text: "${{ steps.initVars.outputs.ANDROID_BUILD_TIME }}"
                - type: "section"
                  fields: 
                    - type: "mrkdwn"
                      text: "${{ steps.initVars.outputs.IOS_STATUS_ICON }} *iOS*"
                    - type: "mrkdwn"
                      text: "${{ steps.initVars.outputs.IOS_BUILD_TIME }}"
                - type: "divider"
                - type: "section"
                  fields: 
                    - type: "mrkdwn"
                      text: "*Branch:*\n${{ inputs.branch }}"
                    - type: "mrkdwn"
                      text: "*Developer info:*\n<${{ inputs.github-action-url }}|GitHub Action>"
