name: "Hello World"
description: "Greet someone"
inputs:
  slack-bot-token:
    description: "Slack bot token"
    required: true
  slack-channel-id:
    description: "Slack channel id"
    required: true
  slack-ts:
    description: "update slack message"
    required: false
    default: ""
  android-status:
    description: "[start|success|fail|cancel]"
    required: false
    default: "start"
  ios-status:
    description: "[start|success|fail|cancel]"
    required: false
    default: "start"
  android-build-time:
    description: ""
    required: false
    default: ""
  ios-build-time:
    description: ""
    required: false
    default: ""
  github-action-url:
    description: ""
    required: false
    default: ""
  version-nr:
    description: ""
    required: false
    default: ""
  branch:
    description: ""
    required: false
    default: ""
outputs:
  ts:
    description: "Slack message timestamp"
    value: ${{ steps.launch_sequence.outputs.ts }}
runs:
  using: "composite"
  steps:
    - name: Create variables for next job
      run: |
	    STATUS=$(
          if [[ "${{ inputs.android-status }}" == "success" && "${{ inputs.ios-status }}" == "success" ]]; then
            echo "success"
          elif [[ "${{ inputs.android-status }}" == "fail" && "${{ inputs.ios-status }}" == "fail" ]]; then
            echo "fail"
          elif [[ "${{ inputs.android-status }}" == "cancel" && "${{ inputs.ios-status }}" == "cancel" ]]; then
            echo "cancel"
          else
            echo "start"
          fi
        )
        STATUS_TEXT=$(
          case "$STATUS" in
            start) echo "in progress" ;;
            success) echo "succeeded" ;;
            fail) echo "failed" ;;
            cancel) echo "canceled" ;;
          esac
        )
        STATUS_COLOR=$(
          case "$STATUS" in
            start) echo "28a745" ;;
            success) echo "dbab09" ;;
            fail) echo "000000" ;;
            cancel) echo "A1A1A1" ;;
          esac
        )
        echo "STATUS=$STATUS" >> $GITHUB_OUTPUT
        echo "STATUS_TEXT=$STATUS_TEXT" >> $GITHUB_OUTPUT
        echo "STATUS_COLOR=$STATUS_COLOR" >> $GITHUB_OUTPUT
        echo "Latest Version Name: $STATUS"
        echo "Latest Version Code: $STATUS_TEXT"
        echo "Latest Version Code: $STATUS_COLOR"

    - name: Send or update slack message
      id: launch_sequence
      uses: slackapi/slack-github-action@v2.0.0
      with:
        method: ${{ inputs.slack-ts && 'chat.update' || 'chat.postMessage' }}
        token: ${{ inputs.slack-bot-token }}
        errors: true
        payload: |
          channel: ${{ inputs.slack-channel-id }}
          ${{ inputs.slack-ts && format('ts: {0}', inputs.slack-ts) || '' }}
          attachments:
            - color: ${{ steps.initVars.outputs.STATUS_TEXT }}
              blocks:
                - type: "section"
                  text: 
                    type: "mrkdwn"
                    text: ":nors: Deployment ${{ steps.initVars.outputs.STATUS_TEXT }}"
                - type: "section"
                  text: 
                    type: "mrkdwn"
                    text: "*Branch:* feature/DEV-3077-deploy-2"
                - type: "section"
                  fields: 
                    - type: "mrkdwn"
                      text: "*Version:* 1.0.4"
                    - type: "mrkdwn"
                      text: "<https://example.com|GitHub Action>"
                - type: "divider"
                - type: "section"
                  fields: 
                    - type: "mrkdwn"
                      text: ":octagonal_sign: *Android:*"
                    - type: "mrkdwn"
                      text: "*Build time:* 53min"
                - type: "section"
                  fields: 
                    - type: "mrkdwn"
                      text: ":octagonal_sign: *iOS:*"
                    - type: "mrkdwn"
                      text: "*Build time:* 53min"
                - type: "section"
                  text: 
                    type: "mrkdwn"
                    text: ":octagonal_sign: :boom: :rocket: :white_check_mark: :heavy_multiplication_x: iOS:"
