name: "Hello World"
description: "Greet someone"
inputs:
  slack-bot-token:
    description: "Slack bot token"
    required: true
  slack-channel-id:
    description: "Slack channel id"
    required: true
  slack-ts:
    description: "update slack message"
    required: false
    default: ""
  android-status:
    description: "[start|success|fail|cancel]"
    required: false
    default: "start"
  ios-status:
    description: "[start|success|fail|cancel]"
    required: false
    default: "start"
  android-build-time:
    description: ""
    required: false
    default: ""
  ios-build-time:
    description: ""
    required: false
    default: ""
  github-action-url:
    description: ""
    required: false
    default: ""
  version-nr:
    description: ""
    required: false
    default: ""
  branch:
    description: ""
    required: false
    default: ""
outputs:
  ts:
    description: "Slack message timestamp"
    value: ${{ steps.launch_sequence.outputs.ts }}
runs:
  using: "composite"
  steps:
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: Create variables for next job
      run: setVariables.sh
      shell: bash
      id: initVars
      env:
        ANDROID_STATUS: ${{ inputs.android-status }}
        IOS_STATUS: ${{ inputs.ios-status }}
        SLACK_BOT_TOKEN: ${{ inputs.slack-bot-token }}
        SLACK_CHANNEL_ID: ${{ inputs.slack-channel-id }}
        ANDROID_BUILD_TIME: ${{ inputs.android-build-time }}
        IOS_BUILD_TIME: ${{ inputs.ios-build-time }}
        GITHUB_ACTION_URL: ${{ inputs.github-action-url }}
        VERSION_NR: ${{ inputs.version-nr }}
        BRANCH: ${{ inputs.branch }}

    - name: Send or update slack message
      id: launch_sequence
      uses: slackapi/slack-github-action@v2.0.0
      with:
        method: ${{ inputs.slack-ts && 'chat.update' || 'chat.postMessage' }}
        token: ${{ inputs.slack-bot-token }}
        errors: false
        payload: |
          channel: ${{ inputs.slack-channel-id }}
          ${{ inputs.slack-ts && format('ts: {0}', inputs.slack-ts) || '' }}
          attachments:
            - color: ${{ steps.initVars.outputs.STATUS_TEXT }}
              blocks:
                - type: "section"
                  text: 
                    type: "mrkdwn"
                    text: ":nors: Deployment ${{ steps.initVars.outputs.STATUS_TEXT }}"
                - type: "section"
                  fields: 
                    - type: "mrkdwn"
                      text: "*Version:* 1.0.4"
                    - type: "mrkdwn"
                      text: "<https://example.com|GitHub Action>"
                - type: "section"
                  fields: 
                    - type: "mrkdwn"
                      text: "${{ steps.initVars.outputs.ANDROID_STATUS_ICON }} *Android:*"
                    - type: "mrkdwn"
                      text: "*Build time:* 53min"
                - type: "section"
                  fields: 
                    - type: "mrkdwn"
                      text: "${{ steps.initVars.outputs.IOS_STATUS_ICON }} *iOS:*"
                    - type: "mrkdwn"
                      text: "*Build time:* 53min"
                - type: "divider"
                - type: "section"
                  text: 
                    type: "mrkdwn"
                    text: "*Branch:* feature/DEV-3077-deploy-2"
