name: "Hello World"
description: "Greet someone"
inputs:
  who-to-greet:
    description: "Who to greet"
    required: true
    default: "World"
  slack-bot-token:
    description: "Slack bot token"
    required: true
  slack-channel-id:
    description: "Slack channel id"
    required: true
  slack-ts:
    description: "update slack message"
    required: false
    default: ""
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
  ts:
    description: "Slack message timestamp"
    value: ${{ steps.launch_sequence.outputs.ts }}
runs:
  using: "composite"
  steps:
    - name: Set Greeting
      run: echo "Hello $INPUT_WHO_TO_GREET."
      shell: bash
      env:
        INPUT_WHO_TO_GREET: ${{ inputs.who-to-greet }}

    - name: Random Number Generator
      id: random-number-generator
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: Run goodbye.sh
      run: goodbye.sh
      shell: bash

    - name: Update the original message with success
      id: launch_sequence
      uses: slackapi/slack-github-action@v2.0.0
      with:
        method: ${{ inputs.slack-ts && 'chat.update' || 'chat.postMessage' }}
        token: ${{ inputs.slack-bot-token }}
        errors: true
        payload: |
          channel: ${{ inputs.slack-channel-id }}
          ${{ inputs.slack-ts && format('ts: {0}', inputs.slack-ts) || '' }}
          text: ":nors: Deployment ${{ inputs.slack-ts && '"completed"' || '"in Progress"' }}"
          attachments:
            - color: ${{ inputs.slack-ts && '"28a745"' || '"dbab09"' }}
              blocks: 
                - type": "section",
                  text: 
                    type: "mrkdwn",
                    text: ":nors: Deployment in progress"
                - type: "section"
                  text: 
                    type: "mrkdwn"
                    text: "*Branch:* feature/DEV-3077-deploy-2"
                - type: "section"
                
                - fields: 
                  - type: "mrkdwn"
                    text: "*Version:* 1.0.4"
                  - type: "mrkdwn"
                    text: "<https://example.com|GitHub Action>"
                - type: "divider"
                - type: "section"
                  fields: 
                    - type: "mrkdwn"
                      text: ":octagonal_sign: *Android:*"
                    - type: "mrkdwn"
                      text: "*Build time:* 53min"
                - type: "section"
                  fields: 
                    - type: "mrkdwn"
                      text: ":octagonal_sign: *iOS:*"
                    - type: "mrkdwn"
                      text: "*Build time:* 53min"
                - type: "section"
                  text: 
                    type: "mrkdwn"
                    text: ":octagonal_sign: :boom: :rocket: :white_check_mark: :heavy_multiplication_x: iOS:"
