name: "Hello World"
description: "Greet someone"
inputs:
  who-to-greet:
    description: "Who to greet"
    required: true
    default: "World"
  slack-bot-token:
    description: "Slack bot token"
    required: true
  slack-channel-id:
    description: "Slack channel id"
    required: true
  slack-ts:
    description: "update slack message"
    required: false
    default: ""
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
  ts:
    description: "Slack message timestamp"
    value: ${{ steps.launch_sequence.outputs.ts }}
runs:
  using: "composite"
  steps:
    - name: Set Greeting
      run: echo "Hello $INPUT_WHO_TO_GREET."
      shell: bash
      env:
        INPUT_WHO_TO_GREET: ${{ inputs.who-to-greet }}

    - name: Random Number Generator
      id: random-number-generator
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: Run goodbye.sh
      run: goodbye.sh
      shell: bash

    - name: Update the original message with success
      uses: slackapi/slack-github-action@v2.0.0
      if: ${{ inputs.slack-ts }}
      with:
        method: ${{ inputs.slack-ts && 'chat.update' || 'chat.postMessage' }}
        token: ${{ inputs.slack-bot-token }}
        payload: |
          channel: ${{ inputs.slack-channel-id }}
          ${{ inputs.slack-ts && 'ts: "${{ inputs.slack-ts }}"' || '' }}
          text: "Deployment finished! :rocket:"
          attachments:
            - color: ${{ inputs.slack-ts && "28a745" || "dbab09" }}
              fields:
                - title: "Status"
                  short: true
                  value: ${{ inputs.slack-ts && "Completed" || "In Progress" }}
